### ISSUE TITLE
Crashing on Export

### ISSUE THREAD

**Issue by YourSandwich** [DATL4G/DXVKoTool#2] opened 2022-09-06 15:17 UTC
Hi,
Pressing on Export, pop ups the Save window(not responsive) and crashes short after this

Specs:
ArchLinux 5.19.7
KDE Plasma 5.25.4
Ryzen 5 3600X
NVIDIA 1080TI on x11 session
2x16GB 3200MHz cl14

Log File:
[hs_err_pid576009.log](https://github.com/DATL4G/DXVKoTool/files/9498320/hs_err_pid576009.log)

**Comment by DATL4G** [comment] 2022-09-06 16:51
Seems like I write try to write the file while I'm still in the main thread.

Should be an easy fix.

**Comment by YourSandwich** [comment] 2022-09-06 17:34
:) let me know if you need more info

**Comment by DATL4G** [comment] 2022-09-06 21:11
Please try the new release v0.1.1.
If it doesn't work fell free to re-open this issue

**Comment by YourSandwich** [comment] 2022-09-06 21:37
Still crashing :(
[hs_err_pid2022211.log](https://github.com/DATL4G/DXVKoTool/files/9501025/hs_err_pid2022211.log)

**Comment by DATL4G** [comment] 2022-09-06 21:40
I'll reproduce your setup and test it

**Comment by DATL4G** [comment] 2022-09-06 21:56
Can you please tell me the ```freetype``` version you've installed

**Comment by YourSandwich** [comment] 2022-09-06 22:29
2.12.1-1

**Comment by DATL4G** [comment] 2022-09-06 22:32
There (was) an issue in version ```2.11.1-1``` which may still exist.

If it's possible try to downgrade to ```2.10.4+dfsg-1``` and look if it's still not working.

Sadly there is not much I can do about it now

**Comment by YourSandwich** [comment] 2022-09-06 22:40
Downgraded and it still don't work :/
[hs_err_pid1011972.log](https://github.com/DATL4G/DXVKoTool/files/9501331/hs_err_pid1011972.log)

**Comment by DATL4G** [comment] 2022-09-06 22:50
Aight you can upgrade it again, I'll implement another File Dialog but that may take some time :|

**Comment by YourSandwich** [comment] 2022-09-06 22:58
Ok im here if you need somethin

**Comment by DATL4G** [comment] 2022-09-06 23:59
I got it faster than I thought.

I would like you to test it.
If you have IntelliJ installed checkout the develop branch and run it.
If you don't have IntelliJ, I can compile and provide a AppImage

**Comment by YourSandwich** [comment] 2022-09-07 08:24
Thank you, i want to learn to compile it myself but i am not using IntelliJ so lets see :)
Just in case, you could compile the AppImage.

**Comment by YourSandwich** [comment] 2022-09-07 08:34
It seemed very easy to compile with gradle, but it just provided me with an "DXVKoTool-0.1.1.jar" that has "no main manifest attribute" :/

**Comment by YourSandwich** [comment] 2022-09-07 08:41
Anyway, i was able to run it with "./gradlew run" and the export now works, unfortunately its not an native windows anymore but the ugly java one :D

**Comment by YourSandwich** [comment] 2022-09-07 08:53
Next issue, when i press on Download. It says "unknown error" and crashes with the following expection:

```
Exception in thread "DefaultDispatcher-worker-51" dev.datlag.dxvkotool.other.DownloadException$InvalidFile
        at dev.datlag.dxvkotool.other.DownloadException$InvalidFile.<clinit>(AppException.kt)
        at dev.datlag.dxvkotool.dxvk.DxvkStateCache$downloadCache$1$1.invokeSuspend(DxvkStateCache.kt:100)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:233)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.awt.ComposeLayer$coroutineExceptionHandler$1@3d48bb99, androidx.compose.runtime.BroadcastFrameClock@6545033c, StandaloneCoroutine{Cancelling}@6ef87cf0, Dispatchers.IO]
```

**Comment by DATL4G** [comment] 2022-09-07 09:03
Yes there is currently a bug in AWTWindow it looks like so all I can do is this ugly java file chooser when you're not using GNOME.
Maybe I can improve the looking a little bit.

But the issue is resolved now thanks for reporting and testing

**Comment by DATL4G** [comment] 2022-09-07 09:04
I created another issue for the download thing as it's not related to this.

Closing

**Closed by DATL4G** 2022-09-07 09:04 UTC
Labels: good first issue
